project:
  type: website

website:
  title: "Zackary Davis | Bioinformatics"
  site-url: https://ZackBioData.github.io
  description: "A living logbook and blog documenting my journey through bioinformatics, machine learning, and scientific discovery."

  navbar:
    left:
      - text: "Logbook"
        href: log/index.qmd
      - text: "Blog"
        href: blog/index.qmd

format:
  html:
    theme: cosmo
    toc: true
